
# Ruta del archivo de texto
text.file.path=./data/textFile.txt

# Ruta del archivo binario
binary.file.path=./data/binaryFile.dat

# Ruta del archivo XML
xml.file.path=./data/xmlFile.xml



